vigna/webgraph-rs

build.rs

This change make build.rs slightly more robust, in particular it informs cargo that it needs to be rebuilt if the generator python script changes and/or when the generated file themselves disappear.
It is still not ideal, because currently we are not following the build.rs recommendation [1] (e.g., we should generate code under env::var_os("OUT_DIR") and include() it from real Rust modules like in [2], rather than generating the actual modules under src), but it's an improvement over the status quo.
[1]: https://doc.rust-lang.org/cargo/reference/build-scripts.html
[2]: https://doc.rust-lang.org/cargo/reference/build-script-examples.html

make build.rs be rebuilt upon generator change

---

code_tables_generator.py
code_tables_plot.py
code_tables_study.py
coverage.py

No semantic changes, with on exception: in code_tables_plot.py an extra
parameter was being passed to the error bar plot but was unused, and spotted as
such by Flake8. It has been removed as part of this commit.

make all Python build scripts Flake8- and Black- clean

---

src/utils/sort_pairs.rs

It allows passing SortPairs (eg. produced by different threads) to KMergeIters to produce a full sorted list

Implement SortedIterator for KMergeIters

---

src/bin/recompress.rs
src/bin/transpose.rs
src/graph/bvgraph/bvgraph_writer_par.rs
src/utils/coo_to_graph.rs
tests/test_par_bvcomp.rs
tests/transpose.rs

So the number of nodes doesn't need to be carried alongside it

Implement ExactSizeIterator for SortedNodePermutedIterator

---

src/algorithms/llp.rs

According to https://doc.rust-lang.org/std/marker/trait.Sync.html :
1. "T is Sync if and only if &T is Send"
2. "&T and &mut T are Sync if and only if T is Sync"
therefore:
* `for<'a> &'a G: Send + Sync` implies `for<'a> &'a G: Send`, which implies `G: Sync` (because of 1)
* `G: Sync` implies "&T and &mut T are Sync" (according to 2), which implies `for<'a> &'a G: Sync`
therefore, `for<'a> &'a G: Send + Sync` is equivalent to `G: Sync`.

layered_label_propagation: Simplify type annotation

---

src/bin/llp.rs

without this patch:
```
$ cargo run --bin llp /tmp/bvgraph perm --gammas "-0,-1,-2,-3,-4"
Finished dev [unoptimized + debuginfo] target(s) in 0.06s
Running `target/debug/llp /tmp/bvgraph perm --gammas -0,-1,-2,-3,-4`
error: unexpected argument '-0' found
tip: to pass '-0' as a value, use '-- -0'
```

bin/llp: Allow negative --gamma values

---

Cargo.lock
Cargo.toml
tests/test_bvcomp.rs
tests/test_par_bvcomp.rs
tests/transpose.rs

Tests concerned: test_bvcomp, test_par_bvcomp, transpose
Rationale: all these tests had very verbose logging (e.g., what each thread is doing) on stderr by default, completely dominating the amount of test output. With this change they log to the env_logger instead, which by default is silent. In case of test failure, the test can be rerun with output with something like:
RUST_LOG=info cargo t -- --nocapture

Migrate test cases with verbose stderr logging to env_logger

---

src/cli/build/ef.rs
src/cli/build/offsets.rs
src/utils/mod.rs

I copy-pasted these functions in swh-graph so I could use them there, and made two  changes:
* Represent paths as PathBuf instead of String
* Add context to errors
This PR imports these changes, and makes the two functions public so I can call them from swh-graph without copying the code or going building an `ArgsMatch` value.

build/{ef,offsets}: Import changes from swh-graph

---

src/cli/align.rs
src/cli/mod.rs
src/cli/pad.rs
src/main.rs
src/utils/mmap_backend.rs

This PR adds Windows specific code to zero pad a file if the required memory map size is bigger than the file as per [CreateFileMappingW](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-createfilemappingw#remarks) contract.
In `load_mut` and `new` the file is already extended by the OS but not 0-initialized, whereas `load` fails to create an mmap with a size larger than the exact file size.

Zero pad file to enforce CreateFileMappingW contract

---

Cargo.toml

It is required since d96bc8ce8a14ef361d1633bdcbce388bfdf7ba27

Fix minimum dsi-progress-logger version

---

src/lib.rs
src/main.rs

This allows downstream crates to access it, and write the string to their own CLIs and metadata files

Make version_string() public

---

src/cli/ascii_convert.rs
src/cli/bfs.rs
src/cli/check_ef.rs
src/cli/from_csv.rs
src/cli/llp.rs
src/cli/merge_perms.rs
src/cli/optimize_codes.rs
src/cli/pad.rs
src/cli/rand_perm.rs
src/cli/recompress.rs
src/cli/simplify.rs
src/cli/to_csv.rs
src/cli/transpose.rs

So they can be 're-exported' by other crates without having to instruct users to 'cargo install webgraph', and obey these crates' lockfile.
This was already done for the subcommands in `build/` for this reason.
I'm only interested in LLP, but I figured it made sense to do this for all subcommands.

Make all CLI implementations public

---

src/cli/bench/bvgraph.rs

Fixed division by zero during bench for random access when -f flag (first) is enabled
Note: I used std::cmp::max instead of the method max on u64 because it was overrided by the implementation of Iterator for u64 in the crate prelude

Fixed division by zero when flag -f is enabled

---

src/algo/llp/mod.rs

LLP on SWH's graph now needs more than 3TB, which makes it crash in this step when there is anything else running on our 4TB machine that needs significant memory, like a previous version of the graph.
I did not try to benchmark this yet

LLP: mmap labels instead of loading them in memory

---

Cargo.toml

chrono 0.4.40 added a Datelike::quarter method, which [conflicts with a trait provided by arrow-rs](https://github.com/apache/arrow-rs/issues/7196), so some crates requires 'chrono < 0.4.40'

Relax dependency on chrono

---

Cargo.toml

resolver 3 requires dependent crates referencing the git repo to have resolver 3 themselves, which requires edition 2024.
edition 2024 requires rustc 1.85 released last month and non-trivial changes in some of said crates, so it is a bit early to require it now.

Use resolver 2 instead of 3

---

algo/Cargo.toml
cli/Cargo.toml
webgraph/Cargo.toml

There is no reason to depend on edition 2021 yet, and it requires a very recent compiler (1.85, released last month)

Switch from edition 2024 to 2021

---

webgraph/src/graphs/random/er.rs

This is crazy, but despite `<Succ as IntoIterator>::IntoIter` being equivalent to `SuccIntoIter`, the way this was written prevented implementing it on other types.
For example, this code:
```rust
use webgraph::prelude::*;
pub struct Test<I: Iterator>(I);
impl<I: Iterator> Iterator for Test<I> {
type Item = <I as Iterator>::Item;
fn next(&mut self) -> Option<Self::Item> {
self.0.next()
}
}
unsafe impl<I: SortedIterator> SortedIterator for Test<I>
{
}
```
failed with:
```
error[E0119]: conflicting implementations of trait `webgraph::traits::SortedIterator` for type `<webgraph::graphs::random::er::Succ as IntoIterator>::IntoIter`
--> repro.rs:13:1
|
13 | unsafe impl<I: SortedIterator> SortedIterator for Test<I>
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: …
```

Make SortedIterator implementable by other crates

---

webgraph/src/graphs/bvgraph/comp/impls.rs

Same issue as bf1a4c890c1c5bc8c6d647094acf0b62939069a6

Fix wrong endiannes in properties saved by BvComp::parallel_iter

---

webgraph/src/graphs/bvgraph/comp/impls.rs
webgraph/src/graphs/bvgraph/comp/mod.rs

As discussed in https://github.com/vigna/webgraph-rs/pull/103#issuecomment-3349131253
This holds arguments shared by various associated functions, and provides default values
I'm not very happy with this implementation, but I don't see a better way.
In particular, I need both `fn ensure_tmp_dir(&mut self) -> Result<()>` and `fn tmp_dir(&self) -> &PathBuf` because unifying them as a single `fn (&mut self) -> Result<&PathBuf>` function means that the return `PathBuf` still mutably borrows the instance, preventing any other method call.

Add BvCompBuilder
